name: Automatic Testing for Resource Management Web App

on:
  push:
    branches:
      - main  # Workflow will be triggered on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3
    
    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies for the project
      run: npm install

    - name: Run backend tests
      run: npx nyc --nycrc-path .nycrc-backend mocha

    - name: Instrument frontend code (Optional)
      run: npx nyc instrument public instrumented

    - name: Run frontend tests
      run: npx cypress run --config-file=cypress.json
